apiVersion: v1
kind: ConfigMap
metadata:
  name: bills-config
  namespace: bills
data:
  # API configuration
  PORT: "3002"
  NODE_ENV: "production"
  WEB_URL: "http://bills-web-svc"
  # Web configuration
  NEXT_PUBLIC_API_URL: "http://bills-api-svc:3002/api/v1"
  NEXTAUTH_URL: "http://localhost:3000"
  # PostgreSQL
  POSTGRES_DB: "bills_db"
  POSTGRES_USER: "bills"
